//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Gameplay/Input/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""7e72e028-3f74-4d67-9b75-12309f89ce56"",
            ""actions"": [
                {
                    ""name"": ""BallForce"",
                    ""type"": ""Button"",
                    ""id"": ""84425b17-ec6d-43ce-baad-5cacf685707f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftLever"",
                    ""type"": ""Button"",
                    ""id"": ""971a19fd-9e80-497f-bac2-2eb828fc6a5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RigthLever"",
                    ""type"": ""Button"",
                    ""id"": ""eac16f2a-ea96-4d17-a442-71f13345c93c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3ee11d5-dc85-4390-a187-4a8e10e05743"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BallForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60096867-f8c3-4e88-a990-65d284809f32"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftLever"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b014fda0-bc2d-4c9f-a188-248e6265ad06"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RigthLever"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_BallForce = m_Gameplay.FindAction("BallForce", throwIfNotFound: true);
        m_Gameplay_LeftLever = m_Gameplay.FindAction("LeftLever", throwIfNotFound: true);
        m_Gameplay_RigthLever = m_Gameplay.FindAction("RigthLever", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_BallForce;
    private readonly InputAction m_Gameplay_LeftLever;
    private readonly InputAction m_Gameplay_RigthLever;
    public struct GameplayActions
    {
        private @InputMap m_Wrapper;
        public GameplayActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @BallForce => m_Wrapper.m_Gameplay_BallForce;
        public InputAction @LeftLever => m_Wrapper.m_Gameplay_LeftLever;
        public InputAction @RigthLever => m_Wrapper.m_Gameplay_RigthLever;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @BallForce.started += instance.OnBallForce;
            @BallForce.performed += instance.OnBallForce;
            @BallForce.canceled += instance.OnBallForce;
            @LeftLever.started += instance.OnLeftLever;
            @LeftLever.performed += instance.OnLeftLever;
            @LeftLever.canceled += instance.OnLeftLever;
            @RigthLever.started += instance.OnRigthLever;
            @RigthLever.performed += instance.OnRigthLever;
            @RigthLever.canceled += instance.OnRigthLever;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @BallForce.started -= instance.OnBallForce;
            @BallForce.performed -= instance.OnBallForce;
            @BallForce.canceled -= instance.OnBallForce;
            @LeftLever.started -= instance.OnLeftLever;
            @LeftLever.performed -= instance.OnLeftLever;
            @LeftLever.canceled -= instance.OnLeftLever;
            @RigthLever.started -= instance.OnRigthLever;
            @RigthLever.performed -= instance.OnRigthLever;
            @RigthLever.canceled -= instance.OnRigthLever;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnBallForce(InputAction.CallbackContext context);
        void OnLeftLever(InputAction.CallbackContext context);
        void OnRigthLever(InputAction.CallbackContext context);
    }
}
